import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawnSync, spawn } from 'node:child_process';
import { recordSessionWriteEvent as record, sessionWriteFiles, consumeSessionWrites, safeEditTarget, decodeEditManifest, sessionWriteJournalDiagnostics } from '../scripts/lib/session-write-journal.mjs';
import { executeContextReview, reviewPromptPlan } from '../scripts/lib/review-engine.mjs';
import { fingerprintSourcesInRoot, createFingerprintCache } from '../scripts/lib/source-fingerprints.mjs';
import { reconcileReviews, claimReviewFindings, readReviewState, finishSessionReviews, reviewQueueDiagnostics } from '../scripts/lib/auto-review-state.mjs';
import { reviewFinding } from '../scripts/lib/review-findings.mjs';
import { updateReviewMetadata } from '../scripts/lib/review-metadata.mjs';
import { documentDependencies } from '../scripts/lib/document-dependencies.mjs';
import { initializeDocumentation } from '../scripts/lib/documentation.mjs';
import { readState, transactState } from '../scripts/lib/state-store.mjs';
import { statePath } from '../scripts/lib/roots.mjs';
import { lerDocumento } from '../scripts/lib/md-hint.mjs';
import { isManagedCodexHook, TARGETS } from '../scripts/lib/setup-targets.mjs';
const plugin = resolve('.');
function fixture(fn) {
  const root = mkdtempSync(join(tmpdir(), 'context-review-v3-'));
  const vars = { CONTEXT_TOOLS_HOST:'codex', CONTEXT_TOOLS_PROJECT_DIR:root, CONTEXT_MAPS_ROOT:root, CONTEXT_TOOLS_SESSION_ID:'a', CONTEXT_TOOLS_TURN_ID:'t1', CONTEXT_TOOLS_STATE_DIR:undefined };
  const old = Object.fromEntries(Object.keys(vars).map(k=>[k,process.env[k]]));
  for (const [k,v] of Object.entries(vars)) v===undefined ? delete process.env[k] : process.env[k]=v;
  try {
    mkdirSync(join(root,'src')); writeFileSync(join(root,'src','a.js'),'export function foo() { return 1; }\nexport function bar() { return 2; }\n');
    writeFileSync(join(root,'src','b.js'),'export const b = 1;\n');
    return fn(root);
  } finally { for (const [k,v] of Object.entries(old)) v===undefined ? delete process.env[k] : process.env[k]=v; rmSync(root,{recursive:true,force:true,maxRetries:5,retryDelay:100}); }
}
const start = (root, session='a')=>record(root,{session_id:session},'--session-start');
function event(session='a',id='e1',file='src/a.js',turn='t1') { return { session_id:session,turn_id:turn,tool_use_id:id,tool_name:'Write',tool_input:{file_path:file},tool_response:{success:true} }; }
function edit(root, session='a', id='e1', text='export function changed() {}\n', file='src/a.js', turn='t1') {
  const e=event(session,id,file,turn); const pre=record(root,e,'--pre-tool-use'); assert.equal(pre.status,'captured');
  writeFileSync(join(root,file),text); return record(root,e,'--post-tool-use');
}
function map(root, files=['src/a.js'], encoding='utf8') {
  const fp=fingerprintSourcesInRoot(root,files); mkdirSync(join(root,'.claude','context'),{recursive:true});
  const path=join(root,'.claude','context','area.md'); const text=`---\r\narea: area\r\ncovers:\r\n${files.map(f=>`  - "${f}"\r\n`).join('')}verified_at: 2020-01-01\r\nsource_fingerprints: ${JSON.stringify(fp.sources)}\r\nsource_digest: ${fp.digest}\r\n---\r\n# Área\r\nInformação preservada.\r\n`;
  writeFileSync(path,encoding==='bom' ? Buffer.concat([Buffer.from([239,187,191]),Buffer.from(text)]) : Buffer.from(text,encoding)); return path;
}
const run=(root,session='a',turn='t1',continuation=false)=>executeContextReview(root,{sessionId:session,turnId:turn,continuation});
test('twenty chats: only latest writer can review, including a content revert',()=>fixture(root=>{
  for(let i=0;i<20;i++) { start(root,`s${i}`); edit(root,`s${i}`,`e${i}`,`export const v = ${i%2};\n`); }
  for(let i=0;i<19;i++) assert.deepEqual(sessionWriteFiles(root,root,`s${i}`,{turnId:'t1'}),[]);
  assert.deepEqual(sessionWriteFiles(root,root,'s19',{turnId:'t1'}),['src/a.js']);
}));
test('resume and next turn do not recover old ownership',()=>fixture(root=>{start(root); edit(root); assert.deepEqual(sessionWriteFiles(root,root,'a',{turnId:'t2'}),[]); start(root); assert.deepEqual(sessionWriteFiles(root,root,'a',{turnId:'t1'}),[]);}));
test('consumed writes cannot reappear on idle Stop',()=>fixture(root=>{start(root); edit(root); consumeSessionWrites(root,'a',{turnId:'t1'}); assert.deepEqual(sessionWriteFiles(root,root,'a'),[]);}));
test('overlapping tools invalidate both claims',()=>fixture(root=>{start(root);start(root,'b');const a=event('a'),b=event('b');record(root,a,'--pre-tool-use');record(root,b,'--pre-tool-use');writeFileSync(join(root,'src/a.js'),'changed');assert.equal(record(root,b,'--post-tool-use').status,'overlapping-edits');assert.equal(record(root,a,'--post-tool-use').status,'overlapping-edits');assert.deepEqual(sessionWriteFiles(root,root,'a'),[]);assert.deepEqual(sessionWriteFiles(root,root,'b'),[]);}));
test('duplicate Post is idempotent and does not count as skipped',()=>fixture(root=>{start(root);edit(root);assert.equal(record(root,event(),'--post-tool-use').status,'already-recorded');assert.equal(sessionWriteJournalDiagnostics(root,'a').skippedEvents,0);}));
test('failed or missing tool response cannot certify writes',()=>fixture(root=>{start(root);const e=event();record(root,e,'--pre-tool-use');writeFileSync(join(root,'src/a.js'),'partial');e.tool_response={exit_code:1};assert.equal(record(root,e,'--post-tool-use').status,'failed-tool');assert.deepEqual(sessionWriteFiles(root,root,'a'),[]);}));
test('unobserved newer bytes remove attribution',()=>fixture(root=>{start(root);edit(root);writeFileSync(join(root,'src/a.js'),'external');assert.deepEqual(sessionWriteFiles(root,root,'a'),[]);}));
test('ordinary shell commands never infer ownership',()=>fixture(root=>{start(root);assert.equal(record(root,{...event(),tool_name:'Bash',tool_input:{command:'node edit.js'}},'--pre-tool-use').status,'ignored-tool');}));
test('manifest validation accepts declared targets and rejects malformed values',()=>{
 const token=Buffer.from(JSON.stringify({version:1,files:['src/a.js']})).toString('base64url'); assert.deepEqual(decodeEditManifest(`node tracked-edit.mjs --context-tools-edit=${token} -- node e.js`),['src/a.js']); assert.equal(decodeEditManifest('node tracked-edit.mjs --context-tools-edit=bad -- node e.js'),null);
});
test('declared sibling repos accepted, unrelated siblings rejected',()=>fixture(root=>{mkdirSync(join(root,'.codex'));const extra=join(root,'..',`${root.split(/[\\/]/).at(-1)}-extra`);mkdirSync(extra);try {writeFileSync(join(extra,'a.js'),'x');writeFileSync(join(root,'.codex','context-tools.json'),JSON.stringify({extraRepos:[`../${extra.split(/[\\/]/).at(-1)}`]}));assert.equal(safeEditTarget(root,join(extra,'a.js')),join(extra,'a.js'));assert.equal(safeEditTarget(root,'../unrelated/a.js'),null);start(root);edit(root,'a','extra','y',join('..',extra.split(/[\\/]/).at(-1),'a.js'));assert.equal(sessionWriteFiles(root,extra,'a').length,1);}finally{rmSync(extra,{recursive:true,force:true});}}));
test('empty current session performs zero source hashing',()=>fixture(root=>{map(root);start(root);const result=run(root);assert.equal(result.cache.reads,0);assert.equal(result.prompt,'');}));
test('automatic review is source-scoped and one bounded continuation',()=>fixture(root=>{map(root);start(root);edit(root);const result=run(root);assert.equal(result.claimed.length,1,JSON.stringify(result.issues));assert.match(result.prompt,/src\/a.js/);const next=run(root,'a','t1',true);assert.equal(next.claimed.length,0);assert.match(next.prompt,/remains pending/);assert.equal(reviewQueueDiagnostics(root).counts.deferred,1);assert.equal(run(root).cache.reads,0);}));
test('source acknowledgement completes only checked version and syncs digest',()=>fixture(root=>{const path=map(root);start(root);edit(root);const first=run(root);const f=first.claimed[0];const updated=updateReviewMetadata(root,f,{checkedKeys:f.sources.map(s=>s.key)});assert.equal(updated.ok,true,updated.message);assert.equal(updated.value.complete,true);const next=run(root,'a','t1',true);assert.equal(next.completed,1);assert.equal(next.prompt,'');assert.match(readFileSync(path,'utf8'),/verified_date:/);}));
test('partial review preserves aggregate digest for unchecked siblings',()=>fixture(root=>{const path=map(root,['src/a.js','src/b.js']);const old=readFileSync(path,'utf8').match(/source_digest: (.+)/)[1];start(root);edit(root);writeFileSync(join(root,'src/b.js'),'external sibling');const f=run(root).claimed[0];assert.equal(f.sources.length,1);const out=updateReviewMetadata(root,f,{checkedKeys:['src/a.js']});assert.equal(out.ok,true,out.message);assert.equal(out.value.complete,false);assert.match(readFileSync(path,'utf8'),new RegExp(old));}));
test('changed source or changed reference refuses acknowledgement',()=>fixture(root=>{const path=map(root);start(root);edit(root);const f=run(root).claimed[0];writeFileSync(join(root,'src/a.js'),'newer');assert.equal(updateReviewMetadata(root,f,{checkedKeys:['src/a.js']}).ok,false);writeFileSync(path,readFileSync(path,'utf8').replace('"src/a.js"','"src/b.js"'));assert.equal(updateReviewMetadata(root,f,{checkedKeys:['src/a.js']}).ok,false);}));
for (const encoding of ['utf8','bom','latin1','utf16le']) test(`metadata acknowledgement preserves ${encoding} encoding and CRLF`,()=>fixture(root=>{const path=map(root,['src/a.js'],encoding);if(encoding==='utf16le')writeFileSync(path,Buffer.concat([Buffer.from([255,254]),readFileSync(path)]));start(root);edit(root);const first=run(root);assert.equal(first.claimed.length,1,JSON.stringify(first.issues));const out=updateReviewMetadata(root,first.claimed[0],{checkedKeys:['src/a.js']});assert.equal(out.ok,true,out.message);const bytes=readFileSync(path);if(encoding==='bom')assert.deepEqual([...bytes.subarray(0,3)],[239,187,191]);if(encoding==='utf16le')assert.deepEqual([...bytes.subarray(0,2)],[255,254]);assert.equal(bytes.includes(Buffer.from([239,191,189])),false);const decoded=lerDocumento(path).text;assert.ok(!/[\r\n]/.test(decoded.replace(/\r\n/g,'')), 'uniform CRLF must remain uniform without doubled CR');}));
test('digest-only sync does not invoke the model or change review date',()=>fixture(root=>{const path=map(root);start(root);edit(root);const current=fingerprintSourcesInRoot(root,['src/a.js']);writeFileSync(path,readFileSync(path,'utf8').replace(/source_fingerprints: .+/,`source_fingerprints: ${JSON.stringify(current.sources)}`));const result=run(root);assert.equal(result.claimed.length,0);assert.equal(result.synchronized,1);assert.match(readFileSync(path,'utf8'),new RegExp(current.digest));assert.doesNotMatch(readFileSync(path,'utf8'),/verified_date/);}));
test('new source revision reopens a deferred target, same revision remains quiet',()=>fixture(root=>{map(root);start(root);edit(root);const first=run(root);run(root,'a','t1',true);edit(root,'a','e2','new second version','src/a.js','t2');const second=run(root,'a','t2');assert.equal(second.claimed.length,1);assert.equal(first.claimed[0].id,second.claimed[0].id);assert.notEqual(first.claimed[0].revision,second.claimed[0].revision);}));
test('empty reconciliation is never completion evidence',()=>fixture(root=>{map(root);start(root);edit(root);run(root);reconcileReviews(root,{findings:[],reviewed:[]});assert.equal(reviewQueueDiagnostics(root).counts.claimed,1);finishSessionReviews(root,'a');assert.equal(reviewQueueDiagnostics(root).counts.deferred,1);}));
test('claims never inherit sources from another session in the same queue entry',()=>fixture(root=>{const fp=fingerprintSourcesInRoot(root,['src/a.js','src/b.js']);const doc=join(root,'doc.md');const a=reviewFinding(root,{kind:'document',document:doc,fingerprint:fp,keys:['src/a.js']});const b=reviewFinding(root,{kind:'document',document:doc,fingerprint:fp,keys:['src/b.js']});reconcileReviews(root,{findings:[a,b]});const claim=claimReviewFindings(root,[b],{sessionId:'b'});assert.deepEqual(claim.findings[0].sources.map(s=>s.key),['src/b.js']);}));
test('batch order and subsets preserve stable identities',()=>fixture(root=>{const fp=fingerprintSourcesInRoot(root,['src/a.js','src/b.js']);const path=join(root,'doc.md');const a=reviewFinding(root,{kind:'document',document:path,fingerprint:fp,keys:['src/a.js']});const b=reviewFinding(root,{kind:'document',document:path,fingerprint:fp,keys:['src/b.js']});assert.equal(a.id,b.id);assert.equal(a.revision,b.revision);}));
test('long manifests fall back to a complete CLI reference within prompt budget',()=>fixture(root=>{const f={id:'a'.repeat(64),kind:'map',document:'doc.md',sources:Array.from({length:80},(_,i)=>({key:`src/${i}.js`,path:join(root,'src',`${i}.js`),fingerprint:`sha256:${'b'.repeat(64)}`}))};const plan=reviewPromptPlan(root,[f]);assert.equal(plan.findings.length,1);const prompt=plan.render(plan.findings);assert.ok(prompt.length<=3200);assert.match(prompt,/complete source manifest/);assert.match(prompt,/"sources":80/);}));
test('historical decisions do not trigger live source review',()=>fixture(root=>{initializeDocumentation(root);writeFileSync(join(root,'ai-context','decisions','incident.md'),'# Incident\nSource: ./src/a.js\nlast_reviewed: 2020-01-01\n');start(root);edit(root);const result=run(root);assert.equal(result.claimed.length,0);assert.equal(result.cache.reads,0);}));
test('live policy and same-day legacy metadata require actual source review',()=>fixture(root=>{initializeDocumentation(root);writeFileSync(join(root,'ai-context','features','live.md'),`# Live\nmaintenance: live\nSource: ./src/a.js\nlast_reviewed: ${new Date().toISOString().slice(0,10)}\n`);start(root);edit(root);const result=run(root);assert.equal(result.claimed.length,1,JSON.stringify(result));assert.equal(result.claimed[0].kind,'document');}));
test('shared fingerprint cache reads identical source only once',()=>fixture(root=>{const cache=createFingerprintCache();fingerprintSourcesInRoot(root,['src/a.js'],cache);fingerprintSourcesInRoot(root,['src/a.js'],cache);assert.equal(cache.reads,1);assert.equal(cache.hits,1);}));
test('invalid symbol dependencies fall back explicitly',()=>fixture(root=>{const fp=fingerprintSourcesInRoot(root,['src/a.js']);const deps=documentDependencies({reviewDependencies:JSON.stringify([{source:'src/a.js',symbols:['not a symbol']}])},fp);assert.equal(deps.valid,false);assert.equal(deps.reason,'ambiguous-dependency');}));
test('state transactions fail visibly on corrupt JSON and preserve bytes',()=>fixture(root=>{const path=join(root,'state.json');writeFileSync(path,'{bad');assert.equal(readState(path,()=>({})).reason,'invalid-state');assert.equal(transactState(path,()=>({}),s=>s.x=1).ok,false);assert.equal(readFileSync(path,'utf8'),'{bad');}));
test('global initialization never creates scripts, skill or local hooks',()=>fixture(root=>{const result=spawnSync(process.execPath,[join(plugin,'install-codex.mjs'),root,'--mode=global'],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);for(const path of ['.codex/scripts','.agents/skills/context-tools','.codex/hooks.json'])assert.equal(existsSync(join(root,path)),false);assert.equal(JSON.parse(readFileSync(join(root,'.codex/context-tools-install.json'))).mode,'global');}));
test('global migration preserves unrelated codex-hook commands',()=>fixture(root=>{mkdirSync(join(root,'.codex'));const path=join(root,'.codex/hooks.json');const managed=`node "${join(root,'.codex/scripts/codex-hook.mjs')}" context-docs.mjs --stop-report`;const custom='node "C:/other/codex-hook.mjs" custom';writeFileSync(path,JSON.stringify({hooks:{Stop:[{hooks:[{command:managed},{command:custom}]}]}}));assert.equal(isManagedCodexHook(managed),true);TARGETS.codex.removeManagedProjectHooks(root);assert.deepEqual(JSON.parse(readFileSync(path)).hooks.Stop[0].hooks,[{command:custom}]);}));
test('eight concurrent processes claim a revision only once',async()=>{
 const root=mkdtempSync(join(tmpdir(),'review-concurrent-'));const module=new URL('../scripts/lib/auto-review-state.mjs',import.meta.url).href;const finding={id:'a'.repeat(64),revision:'b'.repeat(64),kind:'map',document:'doc.md',sources:[],allSources:[]};
 try {const seed=spawnSync(process.execPath,['--input-type=module','-e',`import {reconcileReviews} from ${JSON.stringify(module)};reconcileReviews(${JSON.stringify(root)},{findings:[${JSON.stringify(finding)}]});`],{encoding:'utf8'});assert.equal(seed.status,0,seed.stderr);
 const outputs=await Promise.all(Array.from({length:8},(_,i)=>new Promise((res,rej)=>{const child=spawn(process.execPath,['--input-type=module','-e',`import {claimReviewFindings} from ${JSON.stringify(module)};console.log(JSON.stringify(claimReviewFindings(${JSON.stringify(root)},[${JSON.stringify(finding)}],{sessionId:'s${i}'})));`]);let text='';child.stdout.on('data',chunk=>text+=chunk);child.on('error',rej);child.on('close',code=>code?rej(new Error(text)):res(JSON.parse(text)));})));assert.equal(outputs.reduce((n,o)=>n+o.findings.length,0),1);
 }finally{rmSync(root,{recursive:true,force:true,maxRetries:5,retryDelay:100});}
});

test('in-flight newer edits suppress earlier ownership before source bytes change',()=>fixture(root=>{start(root);edit(root);start(root,'b');record(root,event('b','e2'),'--pre-tool-use');assert.deepEqual(sessionWriteFiles(root,root,'a'),[]);}));
test('Post without Pre invalidates older ownership instead of guessing',()=>fixture(root=>{start(root);edit(root);start(root,'b');assert.equal(record(root,event('b','e2'),'--post-tool-use').status,'no-pre-tool-snapshot');assert.deepEqual(sessionWriteFiles(root,root,'a'),[]);}));
test('CLI refuses a stale or omitted review revision',()=>fixture(root=>{map(root);start(root);edit(root);const finding=run(root).claimed[0];for(const revision of [[],['--revision='+ '0'.repeat(64)]]) {const result=spawnSync(process.execPath,[join(plugin,'scripts/review.mjs'),'ack','--id='+finding.id,'--reviewed',...revision],{cwd:root,encoding:'utf8'});assert.equal(result.status,1);assert.match(result.stderr,/revision/);}assert.equal(reviewQueueDiagnostics(root).counts.claimed,1);}));
test('CLI acknowledges an exact inspected revision and continuation stays quiet',()=>fixture(root=>{map(root);start(root);edit(root);const finding=run(root).claimed[0];const result=spawnSync(process.execPath,[join(plugin,'scripts/review.mjs'),'ack','--id='+finding.id,'--revision='+finding.revision,'--reviewed'],{cwd:root,encoding:'utf8'});assert.equal(result.status,0,result.stderr);assert.equal(reviewQueueDiagnostics(root).counts.complete,1);assert.equal(run(root,'a','t1',true).prompt,'');}));
test('Bash wrapper executes declared ANSI edits without recoding bytes',()=>fixture(root=>{
 const path=join(root,'src/a.js');writeFileSync(path,Buffer.from([65,233,13,10]));const token=Buffer.from(JSON.stringify({version:1,files:['src/a.js']})).toString('base64url');const wrapper=join(plugin,'scripts/tracked-edit.mjs');const command=`node "${wrapper}" --context-tools-edit=${token} -- node edit.js`;start(root);const e={...event(),tool_name:'Bash',tool_input:{command}};assert.equal(record(root,e,'--pre-tool-use').status,'captured');const result=spawnSync(process.execPath,[wrapper,'--context-tools-edit='+token,'--',process.execPath,'-e',"require('node:fs').appendFileSync('src/a.js', Buffer.from([66,233,13,10]))"],{cwd:root,encoding:'utf8'});assert.equal(result.status,0,result.stderr);assert.equal(record(root,e,'--post-tool-use').status,'recorded');assert.deepEqual([...readFileSync(path)],[65,233,13,10,66,233,13,10]);
}));
test('symbol scopes ignore unrelated changes only with matching declared dependencies',()=>fixture(root=>{const fp=fingerprintSourcesInRoot(root,['src/a.js']);const metadata={reviewDependencies:JSON.stringify([{source:'src/a.js',symbols:['function foo']}])};const before=documentDependencies(metadata,fp);assert.equal(before.valid,true,JSON.stringify(before));metadata.dependencyFingerprints=JSON.stringify(before.current);writeFileSync(join(root,'src/a.js'),'export function foo() { return 1; }\nexport function bar() { return 999; }\n');const after=documentDependencies(metadata,fingerprintSourcesInRoot(root,['src/a.js']));assert.equal(after.complete,true);writeFileSync(join(root,'src/a.js'),'export function foo() { return 2; }\nexport function bar() { return 999; }\n');assert.equal(documentDependencies(metadata,fingerprintSourcesInRoot(root,['src/a.js'])).complete,false);}));
test('health never claims complete tracking when journal was not initialized',()=>fixture(root=>{initializeDocumentation(root);const result=spawnSync(process.execPath,[join(plugin,'scripts/health.mjs'),'--json'],{cwd:root,encoding:'utf8'});assert.equal(result.status,0,result.stderr);const report=JSON.parse(result.stdout);assert.equal(report.sessionTracking.status,'incomplete');assert.equal(report.sessionTracking.writeAttribution.status,'not-initialized');}));
test('metadata examples inside code fences remain byte-for-byte unchanged',()=>fixture(root=>{initializeDocumentation(root);const path=join(root,'ai-context/features/live.md');const example='```yaml\nsource_fingerprints: {}\nlast_reviewed: 1900-01-01\n```';writeFileSync(path,'# Live\nSource: ./src/a.js\nlast_reviewed: 2020-01-01\n'+example+'\n');start(root);edit(root);const f=run(root).claimed[0];assert.equal(updateReviewMetadata(root,f,{checkedKeys:f.sources.map(s=>s.key)}).ok,true);assert.ok(readFileSync(path,'utf8').includes(example));}));

test('late shared-target additions cannot be acknowledged by an earlier attempt',()=>fixture(root=>{map(root,['src/a.js','src/b.js']);start(root);edit(root);writeFileSync(join(root,'src/b.js'),'pending b');const first=run(root);const finding=first.claimed[0];const extra={...finding,sources:[{...finding.allSources.find(s=>s.key==='src/b.js')}]};reconcileReviews(root,{findings:[extra]});const result=spawnSync(process.execPath,[join(plugin,'scripts/review.mjs'),'ack','--id='+finding.id,'--revision='+finding.revision,'--reviewed'],{cwd:root,encoding:'utf8'});assert.equal(result.status,0,result.stderr);assert.equal(JSON.parse(result.stdout).result.status,'partial');const text=readFileSync(join(root,'.claude/context/area.md'),'utf8');const current=fingerprintSourcesInRoot(root,['src/b.js']);assert.ok(!text.includes(current.sources['src/b.js']));assert.equal(reviewQueueDiagnostics(root).counts.complete,undefined);}));
test('manual retry refreshes stale source and reference manifests',()=>fixture(root=>{map(root);start(root);edit(root);const old=run(root).claimed[0];writeFileSync(join(root,'src/a.js'),'new after review');const result=spawnSync(process.execPath,[join(plugin,'scripts/review.mjs'),'retry','--id='+old.id],{cwd:root,encoding:'utf8'});assert.equal(result.status,0,result.stderr);const entry=readReviewState(root).value.entries[old.id];assert.equal(entry.status,'ready');assert.notEqual(entry.finding.revision,old.revision);}));

test('a warm legacy cache cannot certify an automatic map review',()=>fixture(root=>{const path=map(root);writeFileSync(path,readFileSync(path,'utf8').replace(/^source_fingerprints:.*\r?\n/gm,'').replace(/^source_digest:.*\r?\n/gm,''));start(root);edit(root);const fp=fingerprintSourcesInRoot(root,['src/a.js']);mkdirSync(join(root,'.codex/context-tools'),{recursive:true});const rawKey=path.replace(/\\/g,'/');const key='map:'+(process.platform==='win32'?rawKey.toLowerCase():rawKey);writeFileSync(join(root,'.codex/context-tools/.source-fingerprints.json'),JSON.stringify({format:1,entries:{[key]:{...fp,at:Date.now()}}}));assert.equal(run(root).claimed.length,1);}));
test('invalid map metadata remains actionable for mixed-case source names',()=>fixture(root=>{writeFileSync(join(root,'src/Area.js'),'export const before = 1;');const path=map(root,['src/Area.js']);writeFileSync(path,readFileSync(path,'utf8').replace(/^source_fingerprints:.*$/m,'source_fingerprints: invalid-json'));start(root);edit(root,'a','upper','export const after = 2;','src/Area.js');assert.equal(run(root).claimed.length,1);}));
test('corrupt metrics remain distinguishable from zero usage',()=>fixture(root=>{initializeDocumentation(root);start(root);mkdirSync(join(root,'.codex/context-tools'),{recursive:true});writeFileSync(join(root,'.codex/context-tools/.context-tools-metrics.json'),'{bad');const result=spawnSync(process.execPath,[join(plugin,'scripts/health.mjs'),'--json'],{cwd:root,encoding:'utf8'});assert.equal(result.status,0,result.stderr);const report=JSON.parse(result.stdout);assert.equal(report.metrics.storageStatus,'invalid-state');assert.equal(report.status,'attention');}));

test('global migration recognizes installer-relative hooks and preserves another project',()=>fixture(root=>{mkdirSync(join(root,'.codex'));const path=join(root,'.codex/hooks.json');const relative='node ".codex/scripts/codex-hook.mjs" context-docs.mjs --stop-report';const custom='node "C:/other/.codex/scripts/codex-hook.mjs" context-docs.mjs --stop-report';writeFileSync(path,JSON.stringify({hooks:{Stop:[{hooks:[{command:relative},{command:custom}]}]}}));assert.equal(isManagedCodexHook(relative,root),true);assert.equal(isManagedCodexHook(custom,root),false);TARGETS.codex.removeManagedProjectHooks(root);assert.deepEqual(JSON.parse(readFileSync(path)).hooks.Stop[0].hooks,[{command:custom}]);}));

test('Codex startup routes stale maps without assigning unrelated reviews',()=>fixture(root=>{map(root);writeFileSync(join(root,'src/a.js'),'unattributed newer code');const result=spawnSync(process.execPath,[join(plugin,'scripts/codex-hook.mjs'),'context-maps.mjs','--session-start'],{cwd:root,encoding:'utf8',input:JSON.stringify({cwd:root,session_id:'a',hook_event_name:'SessionStart'}),env:{...process.env,CONTEXT_TOOLS_LANG:'en'}});assert.equal(result.status,0,result.stderr);assert.match(result.stdout,/does not assign a review/);assert.doesNotMatch(result.stdout,/update the map|bump verified_at|source_fingerprints:/);}));

test('metadata insertion preserves an existing mixed-newline body',()=>fixture(root=>{const path=map(root);const body='# Área\r\nLinha um\nLinha dois\r\n';let text=readFileSync(path,'utf8');text=text.slice(0,text.indexOf('# Área'))+body;writeFileSync(path,text);start(root);edit(root);const finding=run(root).claimed[0];assert.equal(updateReviewMetadata(root,finding,{checkedKeys:finding.sources.map(s=>s.key)}).ok,true);assert.ok(readFileSync(path,'utf8').endsWith(body));}));

test('global migration preserves a null hook declaration without throwing',()=>fixture(root=>{mkdirSync(join(root,'.codex'));const path=join(root,'.codex/hooks.json');const text='{"hooks":null,"userSetting":42}';writeFileSync(path,text);assert.equal(TARGETS.codex.removeManagedProjectHooks(root),false);assert.equal(readFileSync(path,'utf8'),text);}));
